[build]
  base = "eco-solaire-occitan"
  command = "npm install && npm run build -- --configuration production"
  publish = "../dist/eco-solaire-occitan"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200