[build]
  base = "eco-solaire-occitan"
  command = "npm install && npm run build -- --configuration production"
  publish = "../dist/eco-solaire-occitan/browser"

[[redirects]]
  from = "/googleffff0f45835ade75.html"
  to = "/googleffff0f45835ade75.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200